%YAML:1.0
# extrinsics and intrinsics per camera
cameras:
    - {T_SC: [0.9999981611636692, 0.0015073856580174844, 0.0011855200369675274, -0.004185052223446946,
              -0.0015114950052909696, 0.999992826596483, 0.0034730589435404786, -0.001405516727567082,
              -0.0011802762935129827, -0.003474844464768063, 0.9999932661792362, 0.013467474797263729,
              0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 480],
       distortion_coefficients: [0.01439635733714173, -0.01711002520064612, -0.00036986015688269, 0.00048400006763507045],
       distortion_type: radialtangential,
       focal_length: [380.4512213951024, 381.4127464040453],
       principal_point: [321.10261911472014, 241.51747260749895]}
    - {T_SC: [0.9999911157249105, 0.001355752071380918, -0.003991291466355369, 0.045819431574659966,
              -0.0013487447136270904, 0.9999975454573546, 0.0017578301862328526, -0.0015268687395930518,
              0.003993664851476377, -0.0017524313359201253, 0.9999904897675114, 0.013674533582431373,
              0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 480],
       distortion_coefficients: [0.006107371863541705, -0.003987995840632171, -0.00020523064025692887, 0.0003013834060957737],
       distortion_type: radialtangential,
       focal_length: [380.9661957919767, 381.838049435172],
       principal_point: [320.3423844598723, 241.25146755593002]}

# additional camera parameters
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0, 1]
    image_delay: 0.0 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online
        do_extrinsics: true # Do we online-calibrate extrinsics?
        do_extrinsics_final_ba: false # Do we online-calibrate extrinsics?
        sigma_r: 0.001 # T_SCi position prior stdev [m]
        sigma_alpha: 0.01 # T_SCi orientation prior stdev [rad]

# the IMU sensor model
imu_parameters:
    used: true # enable IMU
    a_max: 160.0 # acceleration saturation [m/s^2]
    g_max: 10.0 # gyro saturation [rad/s]
    sigma_g_c: 0.00278 # gyro noise density [rad/s/sqrt(Hz)]
    sigma_bg: 0.03 # gyro bias prior [rad/s]
    sigma_a_c: 0.0252 # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_ba: 0.1 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 0.0008 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 0.04 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    a0: [ 0.0, 0.0, 0.0 ] # Initial accelerometer bias [m/s^2]
    g0: [ 0.0, 0.0, 0.0 ] # Initial gyro bias [rad/s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    T_BS:
        [ 1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0 ]

# frontend: detection etc.
frontend_parameters:
    detection_threshold: 30.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 5.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 400 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.55 # minimum field-of-view overlap
    use_cnn: false
    parallelise_detection: true
    num_matching_threads: 8

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 5 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: true # Whether to run a full final BA
    enforce_realtime: true # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.04 # time budget for realtime optimisation [s]
    realtime_num_threads: 2 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 2 # number of threads for the full (background) optimisation

# some options for how and what to output
output_parameters:
    display_matches: true  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    publish_imu_propagated_state: false # Should the state that is propagated with IMU messages be published or just the optimised ones?
    imu_propagated_state_publishing_rate: 40.0

